//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSite.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string _Address {
            get {
                return ResourceManager.GetString("_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string _AgencyCategoryId {
            get {
                return ResourceManager.GetString("_AgencyCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh.
        /// </summary>
        public static string _AgencyTitle {
            get {
                return ResourceManager.GetString("_AgencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn độ tuổi.
        /// </summary>
        public static string _AgeSelect {
            get {
                return ResourceManager.GetString("_AgeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string _BlogCategoryId {
            get {
                return ResourceManager.GetString("_BlogCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bài viết.
        /// </summary>
        public static string _BlogId {
            get {
                return ResourceManager.GetString("_BlogId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thương hiệu.
        /// </summary>
        public static string _BrandId {
            get {
                return ResourceManager.GetString("_BrandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string _CategoryId {
            get {
                return ResourceManager.GetString("_CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng bởi.
        /// </summary>
        public static string _CreatedById {
            get {
                return ResourceManager.GetString("_CreatedById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string _CreatedDate {
            get {
                return ResourceManager.GetString("_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm đi.
        /// </summary>
        public static string _DepartId {
            get {
                return ResourceManager.GetString("_DepartId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ khởi hành.
        /// </summary>
        public static string _DepartureTime {
            get {
                return ResourceManager.GetString("_DepartureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string _Description {
            get {
                return ResourceManager.GetString("_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm đến.
        /// </summary>
        public static string _DestinationId {
            get {
                return ResourceManager.GetString("_DestinationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string _Detail {
            get {
                return ResourceManager.GetString("_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        public static string _DiscountFromDate {
            get {
                return ResourceManager.GetString("_DiscountFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string _DiscountToDate {
            get {
                return ResourceManager.GetString("_DiscountToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string _Email {
            get {
                return ResourceManager.GetString("_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấp cứu.
        /// </summary>
        public static string _Emergency {
            get {
                return ResourceManager.GetString("_Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string _FaqCategoryId {
            get {
                return ResourceManager.GetString("_FaqCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        public static string _FullName {
            get {
                return ResourceManager.GetString("_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotline.
        /// </summary>
        public static string _Hotline {
            get {
                return ResourceManager.GetString("_Hotline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn hình.
        /// </summary>
        public static string _ImageUrl {
            get {
                return ResourceManager.GetString("_ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp.
        /// </summary>
        public static string _Index {
            get {
                return ResourceManager.GetString("_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích hoạt.
        /// </summary>
        public static string _IsActive {
            get {
                return ResourceManager.GetString("_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là Công ty.
        /// </summary>
        public static string _IsCompany {
            get {
                return ResourceManager.GetString("_IsCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nổi bật.
        /// </summary>
        public static string _IsFeature {
            get {
                return ResourceManager.GetString("_IsFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ẩn trên bản đồ.
        /// </summary>
        public static string _IsHideMap {
            get {
                return ResourceManager.GetString("_IsHideMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã.
        /// </summary>
        public static string _Key {
            get {
                return ResourceManager.GetString("_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat.
        /// </summary>
        public static string _Lat {
            get {
                return ResourceManager.GetString("_Lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn .
        /// </summary>
        public static string _Link {
            get {
                return ResourceManager.GetString("_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lng.
        /// </summary>
        public static string _Lng {
            get {
                return ResourceManager.GetString("_Lng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string _Location {
            get {
                return ResourceManager.GetString("_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string _MenuIcon {
            get {
                return ResourceManager.GetString("_MenuIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại.
        /// </summary>
        public static string _MenuTypeKey {
            get {
                return ResourceManager.GetString("_MenuTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ mô tả.
        /// </summary>
        public static string _MetaDescription {
            get {
                return ResourceManager.GetString("_MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ từ khóa.
        /// </summary>
        public static string _MetaKeyword {
            get {
                return ResourceManager.GetString("_MetaKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ tiêu đề.
        /// </summary>
        public static string _MetaTitle {
            get {
                return ResourceManager.GetString("_MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa bởi.
        /// </summary>
        public static string _ModifiedById {
            get {
                return ResourceManager.GetString("_ModifiedById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cập nhật.
        /// </summary>
        public static string _ModifiedDate {
            get {
                return ResourceManager.GetString("_ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string _NewsSearch {
            get {
                return ResourceManager.GetString("_NewsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string _Note {
            get {
                return ResourceManager.GetString("_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấp Cha.
        /// </summary>
        public static string _ParentId {
            get {
                return ResourceManager.GetString("_ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string _Phone {
            get {
                return ResourceManager.GetString("_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí.
        /// </summary>
        public static string _Position {
            get {
                return ResourceManager.GetString("_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết.
        /// </summary>
        public static string _PostId {
            get {
                return ResourceManager.GetString("_PostId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        public static string _Price {
            get {
                return ResourceManager.GetString("_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá khuyến mãi.
        /// </summary>
        public static string _PriceDiscount {
            get {
                return ResourceManager.GetString("_PriceDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục sản phẩm.
        /// </summary>
        public static string _ProductCategoryId {
            get {
                return ResourceManager.GetString("_ProductCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        public static string _ProductId {
            get {
                return ResourceManager.GetString("_ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoảng.
        /// </summary>
        public static string _RouteAbout {
            get {
                return ResourceManager.GetString("_RouteAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoảng cách.
        /// </summary>
        public static string _RouteKm {
            get {
                return ResourceManager.GetString("_RouteKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string _ServiceCategoryId {
            get {
                return ResourceManager.GetString("_ServiceCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn dịch vụ.
        /// </summary>
        public static string _ServiceSelect {
            get {
                return ResourceManager.GetString("_ServiceSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        public static string _Sku {
            get {
                return ResourceManager.GetString("_Sku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp tin.
        /// </summary>
        public static string _SliderId {
            get {
                return ResourceManager.GetString("_SliderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp.
        /// </summary>
        public static string _Sort {
            get {
                return ResourceManager.GetString("_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string _SpecialistCategoryId {
            get {
                return ResourceManager.GetString("_SpecialistCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên khoa.
        /// </summary>
        public static string _SpecialistId {
            get {
                return ResourceManager.GetString("_SpecialistId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string _Title {
            get {
                return ResourceManager.GetString("_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề phụ.
        /// </summary>
        public static string _Title2 {
            get {
                return ResourceManager.GetString("_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại.
        /// </summary>
        public static string _Type {
            get {
                return ResourceManager.GetString("_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại xe.
        /// </summary>
        public static string _TypeCar {
            get {
                return ResourceManager.GetString("_TypeCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lượt xem.
        /// </summary>
        public static string _Viewed {
            get {
                return ResourceManager.GetString("_Viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string _Web {
            get {
                return ResourceManager.GetString("_Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý.
        /// </summary>
        public static string Agency {
            get {
                return ResourceManager.GetString("Agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục khoa.
        /// </summary>
        public static string AgencyCategoryTitle {
            get {
                return ResourceManager.GetString("AgencyCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm được {0} nhân viên.
        /// </summary>
        public static string AgencyFound {
            get {
                return ResourceManager.GetString("AgencyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm.
        /// </summary>
        public static string AgencySearchCategory {
            get {
                return ResourceManager.GetString("AgencySearchCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string AgencySearchKey {
            get {
                return ResourceManager.GetString("AgencySearchKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên khoa.
        /// </summary>
        public static string AgencySearchSpecialist {
            get {
                return ResourceManager.GetString("AgencySearchSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch làm việc chi tiết.
        /// </summary>
        public static string AgentDetail {
            get {
                return ResourceManager.GetString("AgentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đội ngũ bác sỹ khoa.
        /// </summary>
        public static string AgentofSpecialist {
            get {
                return ResourceManager.GetString("AgentofSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÁC SỸ KHÁC CÙNG KHOA.
        /// </summary>
        public static string AgentSimilar {
            get {
                return ResourceManager.GetString("AgentSimilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm được {0} bài viết.
        /// </summary>
        public static string BlogFound {
            get {
                return ResourceManager.GetString("BlogFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt vé.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình.
        /// </summary>
        public static string BoxSetting {
            get {
                return ResourceManager.GetString("BoxSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Breadcrumb_Home {
            get {
                return ResourceManager.GetString("Breadcrumb_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string btBook {
            get {
                return ResourceManager.GetString("btBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string btContactSend {
            get {
                return ResourceManager.GetString("btContactSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tệp tin.
        /// </summary>
        public static string btnUpload {
            get {
                return ResourceManager.GetString("btnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string btSearch {
            get {
                return ResourceManager.GetString("btSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gọi ngay.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại thông tin.
        /// </summary>
        public static string ContactSendFail {
            get {
                return ResourceManager.GetString("ContactSendFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi thông tin thành công,  Xin chân thành cảm ơn quý khách.
        /// </summary>
        public static string ContactSendOk {
            get {
                return ResourceManager.GetString("ContactSendOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới.
        /// </summary>
        public static string CreatNew {
            get {
                return ResourceManager.GetString("CreatNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string CustomerRequest {
            get {
                return ResourceManager.GetString("CustomerRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không hợp lệ.
        /// </summary>
        public static string DateTimeInvalid {
            get {
                return ResourceManager.GetString("DateTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string DepositAddress {
            get {
                return ResourceManager.GetString("DepositAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string DepositCustomerContent {
            get {
                return ResourceManager.GetString("DepositCustomerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên của bạn.
        /// </summary>
        public static string DepositCustomerName {
            get {
                return ResourceManager.GetString("DepositCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string DepositCustomerPhone {
            get {
                return ResourceManager.GetString("DepositCustomerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string DepositEmail {
            get {
                return ResourceManager.GetString("DepositEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức.
        /// </summary>
        public static string DepositFormality {
            get {
                return ResourceManager.GetString("DepositFormality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chưa hợp lệ.
        /// </summary>
        public static string EmailAddressValidMes {
            get {
                return ResourceManager.GetString("EmailAddressValidMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÂU HỎI NỔI BẬT.
        /// </summary>
        public static string FaqFeature {
            get {
                return ResourceManager.GetString("FaqFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÂU HỎI MỚI NHẤT.
        /// </summary>
        public static string FaqLastest {
            get {
                return ResourceManager.GetString("FaqLastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THƯ VIỆN HỎI ĐÁP.
        /// </summary>
        public static string Faqs {
            get {
                return ResourceManager.GetString("Faqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại.
        /// </summary>
        public static string FaqSearchCategory {
            get {
                return ResourceManager.GetString("FaqSearchCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi.
        /// </summary>
        public static string FaqSearchKey {
            get {
                return ResourceManager.GetString("FaqSearchKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có một câu hỏi? Hỏi hoặc nhập một thuật ngữ tìm kiếm ở đây..
        /// </summary>
        public static string FaqSearchKeyDesc {
            get {
                return ResourceManager.GetString("FaqSearchKeyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string FCustomerContent {
            get {
                return ResourceManager.GetString("FCustomerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên của bạn.
        /// </summary>
        public static string FCustomerName {
            get {
                return ResourceManager.GetString("FCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string FCustomerPhone {
            get {
                return ResourceManager.GetString("FCustomerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin nổi bật.
        /// </summary>
        public static string FeatureBlogs {
            get {
                return ResourceManager.GetString("FeatureBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string FEmail {
            get {
                return ResourceManager.GetString("FEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chưa hợp lệ.
        /// </summary>
        public static string FPhoneValidMes {
            get {
                return ResourceManager.GetString("FPhoneValidMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang lấy dữ liệu từ hệ thống....
        /// </summary>
        public static string GetDataFromServer {
            get {
                return ResourceManager.GetString("GetDataFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập từ khóa bất kỳ.
        /// </summary>
        public static string InputAnyKey {
            get {
                return ResourceManager.GetString("InputAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập câu hỏi cần tìm.
        /// </summary>
        public static string InputAnyKeyFaq {
            get {
                return ResourceManager.GetString("InputAnyKeyFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐỘI NGŨ BÁC SỸ.
        /// </summary>
        public static string lblAgent {
            get {
                return ResourceManager.GetString("lblAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bệnh viện Đa khoa Buôn Mê Thuột quy tụ đội ngũ chuyên gia, giáo sư, bác sĩ đầu ngành, có nhiều năm kinh nghiệm công tác tại các bệnh viện tuyến đầu trong cả nước và tu nghiệp tại các trung tâm chăm sóc sức khỏe, bệnh viện lớn ở nước ngoài..
        /// </summary>
        public static string lblAgentDesc {
            get {
                return ResourceManager.GetString("lblAgentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ.
        /// </summary>
        public static string lblContactInfo {
            get {
                return ResourceManager.GetString("lblContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string MoreView {
            get {
                return ResourceManager.GetString("MoreView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIN NỔI BẬT.
        /// </summary>
        public static string NewsFeature {
            get {
                return ResourceManager.GetString("NewsFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIN MỚI NHẤT.
        /// </summary>
        public static string NewsLastest {
            get {
                return ResourceManager.GetString("NewsLastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức cùng loại.
        /// </summary>
        public static string NewsSimilar {
            get {
                return ResourceManager.GetString("NewsSimilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THỜI GIAN LÀM VIỆC.
        /// </summary>
        public static string OpenHours {
            get {
                return ResourceManager.GetString("OpenHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Thứ 2 - Thứ 6 &lt;span&gt;8:00 - 17:00&lt;/span&gt;&lt;/p&gt;&lt;p&gt;Thứ 7 &lt;span&gt;9:30 - 12:30&lt;/span&gt;&lt;/p&gt;&lt;p&gt;Chủ nhật &lt;span&gt;9:30 - 15.00&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        public static string OpenHoursDesc {
            get {
                return ResourceManager.GetString("OpenHoursDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu sai.
        /// </summary>
        public static string PasswordCompareFail {
            get {
                return ResourceManager.GetString("PasswordCompareFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không hợp lệ.
        /// </summary>
        public static string PhoneValidMes {
            get {
                return ResourceManager.GetString("PhoneValidMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string PostCategoryTitle {
            get {
                return ResourceManager.GetString("PostCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm được {0} sản phẩm.
        /// </summary>
        public static string ProductFound {
            get {
                return ResourceManager.GetString("ProductFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ nhanh : {0}.
        /// </summary>
        public static string QuickCall {
            get {
                return ResourceManager.GetString("QuickCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string RequesterContent {
            get {
                return ResourceManager.GetString("RequesterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào Bác Sỹ{0}! Tôi có vài câu hỏi về tình trạng sức khỏe của mình. Vui lòng liên hệ tôi sớm nhất. Xin Cảm ơn!.
        /// </summary>
        public static string RequesterContentAgentValue {
            get {
                return ResourceManager.GetString("RequesterContentAgentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào Bác Sỹ ! Tôi có vài câu hỏi về tình trạng sức khỏe của mình. Vui lòng liên hệ tôi sớm nhất. Xin Cảm ơn!.
        /// </summary>
        public static string RequesterContentDefaultValue {
            get {
                return ResourceManager.GetString("RequesterContentDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin của bạn sẽ được giữ kin. Trước khi đặt lịch vui lòng đọc kỹ &lt;a href=&quot;/dieu-khoan-dich-vu&quot;&gt;
        ///    Điều khoản dịch vụ
        ///&lt;/a&gt; và &lt;a href=&quot;/chinh-sach-bao-mat&quot;&gt;Chính sách bảo mật&lt;/a&gt;..
        /// </summary>
        public static string RequesterContentNote {
            get {
                return ResourceManager.GetString("RequesterContentNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào Bác Sỹ ! Tôi có vài câu hỏi về {0}. Vui lòng liên hệ tôi sớm nhất. Xin Cảm ơn!.
        /// </summary>
        public static string RequesterContentSpecialistValue {
            get {
                return ResourceManager.GetString("RequesterContentSpecialistValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lịch hẹn.
        /// </summary>
        public static string RequesterContentTitle {
            get {
                return ResourceManager.GetString("RequesterContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hẹn.
        /// </summary>
        public static string RequesterDate {
            get {
                return ResourceManager.GetString("RequesterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string RequesterEmail {
            get {
                return ResourceManager.GetString("RequesterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string RequesterFullName {
            get {
                return ResourceManager.GetString("RequesterFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string RequesterPhone {
            get {
                return ResourceManager.GetString("RequesterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến mãi.
        /// </summary>
        public static string Sale_Title {
            get {
                return ResourceManager.GetString("Sale_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn nhóm.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - - -.
        /// </summary>
        public static string SelectEmpty {
            get {
                return ResourceManager.GetString("SelectEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn loại .
        /// </summary>
        public static string SelectFaq {
            get {
                return ResourceManager.GetString("SelectFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên Khoa.
        /// </summary>
        public static string SelectSpecialist {
            get {
                return ResourceManager.GetString("SelectSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DỊCH VỤ NỔI BẬT.
        /// </summary>
        public static string ServiceFeature {
            get {
                return ResourceManager.GetString("ServiceFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm được {0} bài viết.
        /// </summary>
        public static string ServiceFound {
            get {
                return ResourceManager.GetString("ServiceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DỊCH VỤ MỚI NHẤT.
        /// </summary>
        public static string ServiceLastest {
            get {
                return ResourceManager.GetString("ServiceLastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ khám chữa bệnh.
        /// </summary>
        public static string ServiceofSpecialist {
            get {
                return ResourceManager.GetString("ServiceofSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bệnh viện cung cấp các dịch vụ y khoa Khám, tư vấn, chữa bệnh và điều trị tất cả các loại bệnh lý theo các chuyên khoa gồm khám chữa bệnh, điều trị nội khoa/ ngoại khoa và các dịch vụ hỗ trợ..
        /// </summary>
        public static string ServiceofSpecialistDesc {
            get {
                return ResourceManager.GetString("ServiceofSpecialistDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string SpecialistDetail {
            get {
                return ResourceManager.GetString("SpecialistDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm được {0} chuyên khoa.
        /// </summary>
        public static string SpecialistFound {
            get {
                return ResourceManager.GetString("SpecialistFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên khoa.
        /// </summary>
        public static string SpecialistMember {
            get {
                return ResourceManager.GetString("SpecialistMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bệnh viện Đa khoa Buôn Mê Thuột được xây dựng theo mô hình bệnh viện – khách sạn, tiêu chuẩn quốc tế với 9 chuyên khoa tổng hợp, hệ thống phòng cấp cứu, hệ thống phòng mổ hiện đại, tiêu chuẩn quốc tế cùng các khu dịch vụ hỗ trợ..
        /// </summary>
        public static string SpecialistMemberDesc {
            get {
                return ResourceManager.GetString("SpecialistMemberDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục khoa.
        /// </summary>
        public static string SpecialistSearchCategory {
            get {
                return ResourceManager.GetString("SpecialistSearchCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập khoa cần tìm.
        /// </summary>
        public static string SpecialistSearchKey {
            get {
                return ResourceManager.GetString("SpecialistSearchKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được để trống.
        /// </summary>
        public static string StringEmptyMessage {
            get {
                return ResourceManager.GetString("StringEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không quá {1} ký tự.
        /// </summary>
        public static string StringLengthMessage {
            get {
                return ResourceManager.GetString("StringLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐỘI NGŨ Y BÁC SỸ.
        /// </summary>
        public static string TeamMember {
            get {
                return ResourceManager.GetString("TeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bệnh viện Đa khoa Buôn Mê Thuột được xây dựng theo mô hình bệnh viện - khách sạn, tiêu chuẩn quốc tế với 9 chuyên khoa, &lt;br /&gt;
        ///                    hệ thống phòng cấp cứu, hệ thống phòng mổ hiện đại, tiêu chuẩn quốc cùng các khu dịch vụ hỗ trợ..
        /// </summary>
        public static string TeamMemberDesc {
            get {
                return ResourceManager.GetString("TeamMemberDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quan tâm.
        /// </summary>
        public static string Wishlist {
            get {
                return ResourceManager.GetString("Wishlist", resourceCulture);
            }
        }
    }
}
